### ISSUE TITLE
Error when trying to scan media folders

### ISSUE THREAD

**Issue by earenson** [bhj/KaraokeEternal#14]
Installation of the server works fantastic on both Raspberry Pi & MacOS, but I'm running into the same issue on both when trying to add songs: 

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'strtok3/lib/type'
Require stack:
- /home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/aiff/AiffParser.js
- /home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/ParserFactory.js
- /home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/core.js
- /home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/index.js
- /home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/server/Scanner/FileScanner/FileScanner.js
- /home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/server/Scanner/FileScanner/index.js
- /home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/server/scannerWorker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/aiff/AiffParser.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/aiff/AiffParser.js',
    '/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/ParserFactory.js',
    '/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/core.js',
    '/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/node_modules/music-metadata/lib/index.js',
    '/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/server/Scanner/FileScanner/FileScanner.js',
    '/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/server/Scanner/FileScanner/index.js',
    '/home/pi/.nvm/versions/node/v12.14.0/lib/node_modules/karaoke-forever/server/scannerWorker.js'
  ]
}
```

I've tried `npm i -g strtok3`, in case it hadn't been installed but that didn't seem to help. Noticed the same issue on both node 12 & 13. Am I missing a dependency perhaps? Thanks!!

**Comment by bhj** [comment]
Thanks for the report! I just published v0.7.4-beta.5 to npm, can you try updating and see if that helps?

**Comment by earenson** [comment]
That fixed it! A thing of beauty... thank you!

**Comment by bhj** [comment]
Thanks for the confirmation and kind words! Don't hesitate with [feature requests](https://github.com/bhj/karaoke-forever/issues/13) as well. There is plenty more to do next year :)
